version: '3'
services:
  lovecraft_letter:
    image: lovecraftletter_game_controller
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - DISPLAY=host.docker.internal:0.0
    stdin_open: true
    tty: true

  initializer:
    image: initializer
    ports:
      - 8082:8082

  effecthandler:
    image: effecthandler
    ports:
      - 8083:8083

  db:
    image: postgres:latest
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
  mongo:
    image: mongo:7.0.9
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123